# Generated by Django 5.2.14 on 2026-05-26 04:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(default=2026)),
                ('periodo_letivo', models.CharField(default='2026.1', max_length=20)),
                ('data_inicio_ajustes_coordenadores', models.DateField()),
                ('data_fim_ajustes_coordenadores', models.DateField()),
                ('data_inicio_solicitacoes_professores', models.DateField()),
                ('data_fim_solicitacoes_professores', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_codigo', models.CharField(max_length=60, unique=True)),
                ('bloco', models.CharField(blank=True, max_length=80)),
                ('capacidade', models.PositiveIntegerField(default=30)),
                ('tipo', models.CharField(choices=[('comum', 'Comum'), ('laboratorio', 'Laboratório'), ('auditorio', 'Auditório')], default='comum', max_length=30)),
                ('recursos_disponiveis', models.CharField(blank=True, help_text='Ex.: Projetor, Ar-condicionado, Quadro', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('turnos_oferecidos', models.CharField(default='Matutino, Vespertino, Noturno', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('coordenador_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('carga_horaria', models.PositiveIntegerField(default=60)),
                ('tipo', models.CharField(choices=[('teorica', 'Teórica'), ('pratica', 'Prática')], default='teorica', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.curso')),
                ('professores', models.ManyToManyField(blank=True, related_name='disciplinas_habilitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nome', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('acao', models.CharField(max_length=30)),
                ('tabela_afetada', models.CharField(max_length=80)),
                ('registro_id', models.CharField(max_length=80)),
                ('dados_anteriores', models.JSONField(blank=True, default=dict)),
                ('dados_novos', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de alteração',
                'verbose_name_plural': 'Histórico de alterações',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('coordenador_geral', 'Coordenador Geral'), ('coordenador_curso', 'Coordenador de Curso'), ('professor', 'Professor')], default='professor', max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especializacao', models.CharField(blank=True, max_length=150)),
                ('disponibilidade', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda'), ('terca', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('sabado', 'Sábado')], max_length=20)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('periodo_letivo', models.CharField(default='2026.1', max_length=20)),
                ('ano', models.PositiveIntegerField(default=2026)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_ministradas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.disciplina')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.sala')),
            ],
            options={
                'ordering': ['dia_semana', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ajuste_coordenador', 'Ajuste do Coordenador'), ('troca_professor', 'Troca solicitada pelo Professor')], max_length=40)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada_coord', 'Aprovada pelo Coordenador'), ('aprovada', 'Aprovada Final'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=30)),
                ('dados_sugeridos', models.JSONField(blank=True, default=dict)),
                ('motivo_resposta', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aula')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], max_length=20)),
                ('numero_alunos', models.PositiveIntegerField(default=0)),
                ('periodo_letivo', models.CharField(default='2026.1', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.curso')),
            ],
            options={
                'unique_together': {('nome', 'curso', 'periodo_letivo')},
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.turma'),
        ),
        migrations.CreateModel(
            name='VinculoUsuarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo usuário/curso',
                'verbose_name_plural': 'Vínculos usuários/cursos',
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
