# Generated by Django 6.0.3 on 2026-04-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_codigo', models.CharField(max_length=20, unique=True)),
                ('bloco', models.CharField(max_length=50)),
                ('capacidade', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('comum', 'Comum'), ('laboratorio', 'Laboratório'), ('auditorio', 'Auditório')], max_length=20)),
                ('recursos_disponiveis', models.JSONField(default=list)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
